class Constants(object):
    ENVIRONMENT = 'DEV1'
    DATA_DIRECTORY = '../data/input_data'
    MAPPINGS_DIRECTORY = '../data/mapping_data'
    APPLICATION_NAME = 'Price_Matching'
    SPARK_MASTER = 'local[*]'
    POSTGRESQL_USER = 'postgres'
    POSTGRESQL_PASSWORD = 'tW5xQh45'
    POSTGRESQL_HOST_IP = 'localhost'
    POSTGRESQL_PORT = '5432'
    POSTGRESQL_DATABASE = 'presales'
    IMM_CLASSIFIER_INPUT_TEMP_LOCATION = '../data/imm_input'
    IMM_CLASSIFIER_INPUT_FILE_LOCATION = '../../imm-classifiers-box/data'

    IMM_CLASSIFIER_INPUT_FILE = '../../imm-classifiers-box/data/input.csv'
    IMM_CLASSIFIER_OUTPUT_FILE = '../../imm-classifiers-box/data/imm-classifier-best/predictions/predictions-input.csv'
    GENERATE_UNSPSC_SHELL_SCRIPT = '../../imm-classifiers-box/genarate_unspsc.sh'
    IMM_CLASSIFIER_OUTPUT_TEMP_LOCATION = '../data/imm_output'
    NDC_OUTPUT_TEMP_LOCATION = '../data/ndc_output'
    CTAKES_PORT = '2222'
    RXNAV_PORT = '4000'
    DOCKERCLIENT_BASE_URL = 'unix://var/run/docker.sock'
    DOCKERCLIENT_TIMEOUT = 10
    PYSPARK_POSTGRES_JAR_LOCATION = '../../postgresql-42.2.6.jar'
    OUTPUT_LOCATION = '../data/output'
